# file: action.yml
# version: 1.0.0
# guid: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e

name: "Generate Semantic Version"
description: "Generate semantic version based on latest git tag and release type"
author: "jdfalk"

branding:
  icon: "tag"
  color: "blue"

inputs:
  release-type:
    description: "Release type (major/minor/patch/auto)"
    required: false
    default: "auto"

  branch-name:
    description: "Git branch name for context"
    required: false
    default: "main"

  prerelease-suffix:
    description: "Prerelease suffix (e.g., 'alpha', 'beta', 'rc')"
    required: false
    default: ""

outputs:
  tag:
    description: "Full semantic version tag (e.g., v1.2.3)"
    value: ${{ steps.version.outputs.tag }}

  version:
    description: "Semantic version without 'v' prefix (e.g., 1.2.3)"
    value: ${{ steps.version.outputs.version }}

  major:
    description: "Major version number"
    value: ${{ steps.version.outputs.major }}

  minor:
    description: "Minor version number"
    value: ${{ steps.version.outputs.minor }}

  patch:
    description: "Patch version number"
    value: ${{ steps.version.outputs.patch }}

  prerelease:
    description: "Prerelease suffix (if any)"
    value: ${{ steps.version.outputs.prerelease }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version
      id: version
      shell: bash
      env:
        RELEASE_TYPE: ${{ inputs.release-type }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        PRERELEASE_SUFFIX: ${{ inputs.prerelease-suffix }}
      run: bash "${{ github.action_path }}/src/generate_version.sh"
